# Spring相关配置
spring:
  # Spring的自动扫描包
  packageScan: ['komics']
---
# 数据库配置: 如果有用到数据库,请打开数据源配置
# 数据源: 默认采用阿里巴巴的 druid data source, 暂不支持其他
datasource:
  -
    # 数据源名字
    name: "default"
    class: "com.alibaba.druid.pool.DruidDataSource"
    url: "jdbc:mysql://localhost:3306/decor_new"
    username: 'root'
    password: 'Qwer!234'
    minIdle: 5
    initialSize: 10
    maxActive: 100
    # 以下配置并不需要经常修改,可以保持为默认值
    maxWait: 60000
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: "wall,stat"
    validationQuery: "SELECT 'x'"
    # 数据库监控: 设置为 true 则打开 druid 的数据库监控配置
    monitor: true